using System;
using StreamVault.Domain.Interfaces;

namespace StreamVault.Domain.Entities
{
    public class Caption : ITenantEntity
    {
        public Guid Id { get; set; }
        public Guid VideoId { get; set; }
        public Video Video { get; set; } = null!;
        public Guid TenantId { get; set; }
        public Tenant Tenant { get; set; } = null!;
        public string Language { get; set; } = null!;
        public string Label { get; set; } = null!;
        public CaptionFormat Format { get; set; }
        public string Content { get; set; } = null!;
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }

    public enum CaptionFormat
    {
        VTT = 1,
        SRT = 2,
        SBV = 3,
        DFXP = 4,
        TTML = 5
    }
}
