using System.ComponentModel.DataAnnotations;

namespace StreamVault.Domain.Entities;

public class VideoThumbnail
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required]
    public Guid VideoId { get; set; }

    public int PositionSeconds { get; set; }

    [Required, MaxLength(500)]
    public string StoragePath { get; set; } = string.Empty;

    public int Width { get; set; }

    public int Height { get; set; }

    public ThumbnailType Type { get; set; } = ThumbnailType.Custom;

    public bool IsDefault { get; set; } = false;

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    // Navigation properties
    public Video Video { get; set; } = null!;
}

public enum ThumbnailType
{
    Default,
    Custom,
    AutoGenerated,
    Sprite,
    Waveform
}
