using System.ComponentModel.DataAnnotations;

namespace StreamVault.Application.Videos.DTOs;

public class CreateChapterRequest
{
    [Required]
    public string Title { get; set; } = string.Empty;
    
    [MaxLength(500)]
    public string? Description { get; set; }
    
    [Required]
    public TimeSpan StartTime { get; set; }
    
    public TimeSpan? EndTime { get; set; }
    
    public string? ThumbnailUrl { get; set; }
    
    public List<string> Tags { get; set; } = new();
    
    public bool IsHidden { get; set; } = false;
    
    public int Order { get; set; } = 0;
}

public class UpdateChapterRequest
{
    public string? Title { get; set; }
    
    public string? Description { get; set; }
    
    public TimeSpan? StartTime { get; set; }
    
    public TimeSpan? EndTime { get; set; }
    
    public string? ThumbnailUrl { get; set; }
    
    public List<string>? Tags { get; set; }
    
    public bool? IsHidden { get; set; }
    
    public int? Order { get; set; }
}

public class VideoChapterDto
{
    public Guid Id { get; set; }
    public Guid VideoId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public TimeSpan StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }
    public TimeSpan Duration => EndTime.HasValue ? EndTime.Value - StartTime : TimeSpan.Zero;
    public string? ThumbnailUrl { get; set; }
    public List<string> Tags { get; set; } = new();
    public bool IsHidden { get; set; }
    public int Order { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public bool IsAutoGenerated { get; set; }
}

public class CreateMarkerRequest
{
    [Required]
    public TimeSpan Time { get; set; }
    
    [Required, MaxLength(100)]
    public string Title { get; set; } = string.Empty;
    
    [MaxLength(300)]
    public string? Description { get; set; }
    
    [Required]
    public string Type { get; set; } = string.Empty; // bookmark, highlight, note, error, etc.
    
    public string? Color { get; set; }
    
    public bool IsPrivate { get; set; } = true;
    
    public Dictionary<string, object>? Metadata { get; set; }
}

public class UpdateMarkerRequest
{
    public TimeSpan? Time { get; set; }
    
    public string? Title { get; set; }
    
    public string? Description { get; set; }
    
    public string? Type { get; set; }
    
    public string? Color { get; set; }
    
    public bool? IsPrivate { get; set; }
    
    public Dictionary<string, object>? Metadata { get; set; }
}

public class VideoMarkerDto
{
    public Guid Id { get; set; }
    public Guid VideoId { get; set; }
    public Guid UserId { get; set; }
    public TimeSpan Time { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public string Type { get; set; } = string.Empty;
    public string? Color { get; set; }
    public bool IsPrivate { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
    public Dictionary<string, object>? Metadata { get; set; }
    public UserDto User { get; set; } = null!;
}

public class ImportChaptersRequest
{
    [Required]
    public string Format { get; set; } = string.Empty; // json, csv, youtube, vtt
    
    [Required]
    public string Content { get; set; } = string.Empty;
    
    public bool ReplaceExisting { get; set; } = false;
    
    public TimeSpan? TimeOffset { get; set; }
}

public class ChapterNavigationDto
{
    public Guid ChapterId { get; set; }
    public string Title { get; set; } = string.Empty;
    public TimeSpan StartTime { get; set; }
    public TimeSpan EndTime { get; set; }
    public string? ThumbnailUrl { get; set; }
    public int Order { get; set; }
    public bool IsActive { get; set; }
}

public class ChapterAnalyticsDto
{
    public Guid ChapterId { get; set; }
    public string Title { get; set; } = string.Empty;
    public int Views { get; set; }
    public double AverageWatchTime { get; set; }
    public double CompletionRate { get; set; }
    public int SkipCount { get; set; }
    public int ReplayCount { get; set; }
    public List<ViewerHeatmapDto> ViewerHeatmap { get; set; } = new();
}

public class ViewerHeatmapDto
{
    public TimeSpan TimeOffset { get; set; }
    public int ViewerCount { get; set; }
    public double Engagement { get; set; }
}

public class ChapterSuggestionDto
{
    public TimeSpan StartTime { get; set; }
    public TimeSpan EndTime { get; set; }
    public string SuggestedTitle { get; set; } = string.Empty;
    public double Confidence { get; set; }
    public string Reason { get; set; } = string.Empty;
    public List<string> Keywords { get; set; } = new();
}

public class BatchChapterRequest
{
    [Required]
    public List<CreateChapterRequest> Chapters { get; set; } = new();
    
    public bool ReplaceExisting { get; set; } = false;
}

public class ChapterExportDto
{
    public Guid VideoId { get; set; }
    public string VideoTitle { get; set; } = string.Empty;
    public List<VideoChapterDto> Chapters { get; set; } = new();
    public TimeSpan TotalDuration { get; set; }
    public int ChapterCount { get; set; }
    public DateTimeOffset ExportedAt { get; set; }
}

public class MarkerSearchRequest
{
    public Guid VideoId { get; set; }
    public string? Type { get; set; }
    public TimeSpan? StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }
    public string? Query { get; set; }
    public bool IncludePrivate { get; set; } = false;
    public Guid? UserId { get; set; }
}

public class MarkerGroupDto
{
    public string Type { get; set; } = string.Empty;
    public string DisplayName { get; set; } = string.Empty;
    public string Color { get; set; } = string.Empty;
    public int Count { get; set; }
    public List<VideoMarkerDto> Markers { get; set; } = new();
}

public class ChapterInteractionDto
{
    public Guid ChapterId { get; set; }
    public Guid UserId { get; set; }
    public TimeSpan WatchTime { get; set; }
    public bool IsCompleted { get; set; }
    public DateTimeOffset LastAccessed { get; set; }
    public int AccessCount { get; set; }
}
