using Microsoft.EntityFrameworkCore;
using StreamVault.Application.Services;
using StreamVault.Application.Thumbnails.DTOs;
using StreamVault.Domain.Entities;
using StreamVault.Infrastructure.Data;
using ThumbnailOptions = StreamVault.Application.Thumbnails.DTOs.ThumbnailOptions;

namespace StreamVault.Application.Thumbnails;

public class ThumbnailGeneratorService : IThumbnailGeneratorService
{
    private readonly StreamVaultDbContext _dbContext;
    private readonly IStorageService _storageService;

    public ThumbnailGeneratorService(StreamVaultDbContext dbContext, IStorageService storageService)
    {
        _dbContext = dbContext;
        _storageService = storageService;
    }

    public async Task<List<VideoThumbnailDto>> GenerateThumbnailsAsync(Guid videoId, GenerateThumbnailsRequest request, Guid userId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId && v.UserId == userId);

        if (video == null)
            throw new Exception("Video not found");

        if (video.DurationSeconds <= 0)
            throw new Exception("Video duration is not available");

        var thumbnails = new List<VideoThumbnailDto>();
        var interval = video.DurationSeconds / request.Count;

        for (int i = 0; i < request.Count; i++)
        {
            var positionSeconds = (int)(i * interval);
            var thumbnail = await GenerateThumbnailAtPositionAsync(videoId, positionSeconds, request.Options, userId, tenantId);
            thumbnails.Add(thumbnail);
        }

        return thumbnails;
    }

    public async Task<VideoThumbnailDto> GenerateThumbnailAtPositionAsync(Guid videoId, int positionSeconds, ThumbnailOptions options, Guid userId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId);

        if (video == null)
            throw new Exception("Video not found");

        // Check if thumbnail already exists at this position
        var existingThumbnail = await _dbContext.VideoThumbnails
            .FirstOrDefaultAsync(vt => vt.VideoId == videoId && vt.PositionSeconds == positionSeconds);

        if (existingThumbnail != null)
        {
            return await MapToDto(existingThumbnail);
        }

        // Generate thumbnail storage path
        var thumbnailPath = $"thumbnails/{videoId}/{positionSeconds}.{options.Format}";
        
        // In a real implementation, you would use a video processing library like FFMPEG to extract frames
        // For now, we'll simulate the thumbnail generation
        var thumbnail = new VideoThumbnail
        {
            Id = Guid.NewGuid(),
            VideoId = videoId,
            PositionSeconds = positionSeconds,
            StoragePath = thumbnailPath,
            Width = options.Width,
            Height = options.Height,
            Type = ThumbnailType.AutoGenerated,
            IsDefault = false,
            CreatedAt = DateTimeOffset.UtcNow
        };

        _dbContext.VideoThumbnails.Add(thumbnail);
        await _dbContext.SaveChangesAsync();

        // In a real implementation, you would:
        // 1. Download the video from storage
        // 2. Use FFMPEG to extract frame at positionSeconds
        // 3. Resize and format the image
        // 4. Upload the thumbnail to storage
        // await _storageService.UploadFileAsync(thumbnailPath, thumbnailData, options.ContentType);

        return await MapToDto(thumbnail);
    }

    public async Task<VideoThumbnailDto> UploadCustomThumbnailAsync(Guid videoId, UploadThumbnailRequest request, Guid userId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId && v.UserId == userId);

        if (video == null)
            throw new Exception("Video not found");

        // Generate thumbnail storage path
        var fileExtension = Path.GetExtension(request.FileName);
        var thumbnailPath = $"thumbnails/{videoId}/custom_{Guid.NewGuid()}{fileExtension}";

        // Upload the thumbnail to storage
        await _storageService.UploadFileAsync(thumbnailPath, request.Data, request.ContentType);

        var thumbnail = new VideoThumbnail
        {
            Id = Guid.NewGuid(),
            VideoId = videoId,
            PositionSeconds = request.PositionSeconds,
            StoragePath = thumbnailPath,
            Width = 0, // Would be determined after processing
            Height = 0, // Would be determined after processing
            Type = ThumbnailType.Custom,
            IsDefault = false,
            CreatedAt = DateTimeOffset.UtcNow
        };

        _dbContext.VideoThumbnails.Add(thumbnail);
        await _dbContext.SaveChangesAsync();

        return await MapToDto(thumbnail);
    }

    public async Task<List<VideoThumbnailDto>> GetThumbnailsAsync(Guid videoId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId);

        if (video == null)
            throw new Exception("Video not found");

        var thumbnails = await _dbContext.VideoThumbnails
            .Where(vt => vt.VideoId == videoId)
            .OrderBy(vt => vt.PositionSeconds)
            .ToListAsync();

        var thumbnailDtos = new List<VideoThumbnailDto>();
        foreach (var thumbnail in thumbnails)
        {
            thumbnailDtos.Add(await MapToDto(thumbnail));
        }
        return thumbnailDtos;
    }

    public async Task SetDefaultThumbnailAsync(Guid videoId, Guid thumbnailId, Guid userId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId && v.UserId == userId);

        if (video == null)
            throw new Exception("Video not found");

        // Clear existing default
        var existingDefaults = await _dbContext.VideoThumbnails
            .Where(vt => vt.VideoId == videoId && vt.IsDefault)
            .ToListAsync();

        foreach (var defaultThumbnail in existingDefaults)
        {
            defaultThumbnail.IsDefault = false;
        }

        // Set new default
        var newDefault = await _dbContext.VideoThumbnails
            .FirstOrDefaultAsync(vt => vt.Id == thumbnailId && vt.VideoId == videoId);

        if (newDefault == null)
            throw new Exception("Thumbnail not found");

        newDefault.IsDefault = true;

        // Update video thumbnail path
        video.ThumbnailPath = newDefault.StoragePath;

        await _dbContext.SaveChangesAsync();
    }

    public async Task DeleteThumbnailAsync(Guid thumbnailId, Guid userId, Guid tenantId)
    {
        var thumbnail = await _dbContext.VideoThumbnails
            .Include(vt => vt.Video)
            .FirstOrDefaultAsync(vt => vt.Id == thumbnailId);

        if (thumbnail == null || thumbnail.Video.TenantId != tenantId || thumbnail.Video.UserId != userId)
            throw new Exception("Thumbnail not found");

        // Don't delete the default thumbnail
        if (thumbnail.IsDefault)
            throw new Exception("Cannot delete the default thumbnail");

        // Delete from storage
        await _storageService.DeleteFileAsync(thumbnail.StoragePath);

        _dbContext.VideoThumbnails.Remove(thumbnail);
        await _dbContext.SaveChangesAsync();
    }

    public async Task<string> GenerateSpriteSheetAsync(Guid videoId, SpriteSheetRequest request, Guid userId, Guid tenantId)
    {
        // Verify video belongs to tenant
        var video = await _dbContext.Videos
            .FirstOrDefaultAsync(v => v.Id == videoId && v.TenantId == tenantId && v.UserId == userId);

        if (video == null)
            throw new Exception("Video not found");

        if (video.DurationSeconds <= 0)
            throw new Exception("Video duration is not available");

        // Generate thumbnails for sprite sheet
        var thumbnails = new List<VideoThumbnailDto>();
        var interval = video.DurationSeconds / request.Count;

        for (int i = 0; i < request.Count; i++)
        {
            var positionSeconds = (int)(i * interval);
            var thumbnail = await GenerateThumbnailAtPositionAsync(videoId, positionSeconds, request.Options, userId, tenantId);
            thumbnails.Add(thumbnail);
        }

        // In a real implementation, you would:
        // 1. Download all thumbnail images
        // 2. Combine them into a sprite sheet using image processing
        // 3. Upload the sprite sheet to storage
        // 4. Return the sprite sheet URL

        var spriteSheetPath = $"thumbnails/{videoId}/sprite_{Guid.NewGuid()}.jpg";
        
        // Simulate sprite sheet generation
        await _storageService.UploadFileAsync(spriteSheetPath, new byte[0], "image/jpeg");

        // Return the presigned URL
        return await _storageService.GetPresignedUrlAsync(spriteSheetPath, TimeSpan.FromDays(7));
    }

    private async Task<VideoThumbnailDto> MapToDto(VideoThumbnail thumbnail)
    {
        var thumbnailUrl = await _storageService.GetPresignedUrlAsync(thumbnail.StoragePath, TimeSpan.FromHours(1));

        return new VideoThumbnailDto
        {
            Id = thumbnail.Id,
            VideoId = thumbnail.VideoId,
            PositionSeconds = thumbnail.PositionSeconds,
            StoragePath = thumbnail.StoragePath,
            ThumbnailUrl = thumbnailUrl,
            Width = thumbnail.Width,
            Height = thumbnail.Height,
            Type = thumbnail.Type,
            IsDefault = thumbnail.IsDefault,
            CreatedAt = thumbnail.CreatedAt
        };
    }
}
